### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by IFIF1727** [zhousinan/WordBookPlusAbout#3]
If I write a long sentence in the translation column, the sentence wiil be not seen at the end.
https://z1.ax1x.com/2023/09/18/pPhzv79.png

**Comment by zhousinan** [comment]
Thank you for your report again! The translation field is used to explain the word briefly, so it is not prepared to display long text. I suggest using the remark field to add more information. If it is possible, I will add a new feature to support multiply lines in translation and I will append comment in this issue in the future! ☺️

**Comment by zhousinan** [comment]
Good news! A new feature which supports multiple line in translation will be available with the update! Thank you again for your suggestion!
